spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livers?createDatabaseIfNotExist=true
    username: root
    password: hamdi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: off
server:
  port: 8082

